import { VillageInfo, ADLItemDefinition, ADLCategoryInfo, LTCGroupInfo, Patient, ADLAssessment } from '../types';

export const VILLAGES: VillageInfo[] = [
  {
    id: 1,
    villageNumber: 1,
    name: 'บ้านธาตุ',
    fullName: 'หมู่ 1 บ้านธาตุ',
    subdistrict: 'ตำบลบ้านธาตุ',
    district: 'อำเภอเมือง',
    province: 'จังหวัดอุดรธานี',
    healthCenter: 'รพ.สต.บ้านธาตุ',
    volunteerLeader: 'นางสมใจ สุขสวัสดิ์ (ประธาน อสม.)',
  },
  {
    id: 2,
    villageNumber: 2,
    name: 'บ้านงินโงม',
    fullName: 'หมู่ 2 บ้านงินโงม',
    subdistrict: 'ตำบลบ้านธาตุ',
    district: 'อำเภอเมือง',
    province: 'จังหวัดอุดรธานี',
    healthCenter: 'รพ.สต.บ้านธาตุ',
    volunteerLeader: 'นายบุญเลิศ มั่นคง (ประธาน อสม.)',
  },
  {
    id: 3,
    villageNumber: 3,
    name: 'บ้านโนนสร้างไพ',
    fullName: 'หมู่ 3 บ้านโนนสร้างไพ',
    subdistrict: 'ตำบลบ้านธาตุ',
    district: 'อำเภอเมือง',
    province: 'จังหวัดอุดรธานี',
    healthCenter: 'รพ.สต.บ้านธาตุ',
    volunteerLeader: 'นางประภาศรี วงศ์ษา (ประธาน อสม.)',
  },
  {
    id: 4,
    villageNumber: 4,
    name: 'บ้านหนองหอย',
    fullName: 'หมู่ 4 บ้านหนองหอย',
    subdistrict: 'ตำบลบ้านธาตุ',
    district: 'อำเภอเมือง',
    province: 'จังหวัดอุดรธานี',
    healthCenter: 'รพ.สต.บ้านธาตุ',
    volunteerLeader: 'นายสมชาย คำมี (ประธาน อสม.)',
  },
  {
    id: 5,
    villageNumber: 5,
    name: 'บ้านคันชา',
    fullName: 'หมู่ 5 บ้านคันชา',
    subdistrict: 'ตำบลบ้านธาตุ',
    district: 'อำเภอเมือง',
    province: 'จังหวัดอุดรธานี',
    healthCenter: 'รพ.สต.บ้านธาตุ',
    volunteerLeader: 'นางทองม้วน ศรีสุข (ประธาน อสม.)',
  },
  {
    id: 6,
    villageNumber: 6,
    name: 'บ้านโคกหลวง',
    fullName: 'หมู่ 6 บ้านโคกหลวง',
    subdistrict: 'ตำบลบ้านธาตุ',
    district: 'อำเภอเมือง',
    province: 'จังหวัดอุดรธานี',
    healthCenter: 'รพ.สต.บ้านธาตุ',
    volunteerLeader: 'นายสุวิทย์ ศรีวิลัย (ประธาน อสม.)',
  },
  {
    id: 7,
    villageNumber: 7,
    name: 'บ้านเดิด',
    fullName: 'หมู่ 7 บ้านเดิด',
    subdistrict: 'ตำบลบ้านธาตุ',
    district: 'อำเภอเมือง',
    province: 'จังหวัดอุดรธานี',
    healthCenter: 'รพ.สต.บ้านธาตุ',
    volunteerLeader: 'นางรำไพ พลเยี่ยม (ประธาน อสม.)',
  },
  {
    id: 8,
    villageNumber: 8,
    name: 'บ้านเดื่อ',
    fullName: 'หมู่ 8 บ้านเดื่อ',
    subdistrict: 'ตำบลบ้านธาตุ',
    district: 'อำเภอเมือง',
    province: 'จังหวัดอุดรธานี',
    healthCenter: 'รพ.สต.บ้านธาตุ',
    volunteerLeader: 'นายอำนวย บุญมี (ประธาน อสม.)',
  },
];

export const ADL_CATEGORIES: Record<string, ADLCategoryInfo> = {
  social: {
    category: 'social',
    title: 'กลุ่มที่ 1: ติดสังคม',
    subtitle: 'พึ่งพาตนเองได้',
    scoreRange: '12 - 20 คะแนน',
    minScore: 12,
    maxScore: 20,
    color: 'emerald',
    bgColor: 'bg-emerald-50 text-emerald-800',
    borderColor: 'border-emerald-300',
    description: 'ผู้สูงอายุ/ผู้ป่วยสามารถช่วยเหลือตัวเองได้ดี ดำเนินชีวิตประจำวันและเข้าร่วมกิจกรรมในชุมชนได้ตามปกติ',
    careGuidelines: 'ส่งเสริมการออกกำลังกาย สุขภาพจิต โภชนาการ และเฝ้าระวังโรคไม่ติดต่อเรื้อรัง (NCDs) ตรวจประเมินซ้ำปีละ 1 ครั้ง',
  },
  homebound: {
    category: 'homebound',
    title: 'กลุ่มที่ 2: ติดบ้าน',
    subtitle: 'พึ่งพาตนเองได้ปานกลาง',
    scoreRange: '5 - 11 คะแนน',
    minScore: 5,
    maxScore: 11,
    color: 'amber',
    bgColor: 'bg-amber-50 text-amber-800',
    borderColor: 'border-amber-300',
    description: 'ผู้สูงอายุ/ผู้ป่วยมีข้อจำกัดในการทำกิจวัตรประจำวัน ต้องการความช่วยเหลือเป็นบางส่วน สามารถเคลื่อนไหวในบ้านได้แต่จำกัดการออกนอกบ้าน',
    careGuidelines: 'จัดบริการดูแลระยะยาว (LTC) จัดผู้ช่วยดูแล (CG) เยี่ยมบ้านอย่างน้อยสัปดาห์ละ 1 ครั้ง กายภาพบำบัดฟื้นฟู และจัดหาอุปกรณ์ช่วยเดิน',
  },
  bedridden: {
    category: 'bedridden',
    title: 'กลุ่มที่ 3: ติดเตียง',
    subtitle: 'พึ่งพาตนเองไม่ได้/พึ่งพาผู้อื่นอย่างมาก',
    scoreRange: '0 - 4 คะแนน',
    minScore: 0,
    maxScore: 4,
    color: 'rose',
    bgColor: 'bg-rose-50 text-rose-800',
    borderColor: 'border-rose-300',
    description: 'ผู้สูงอายุ/ผู้ป่วยไม่สามารถช่วยเหลือตัวเองได้ ต้องนอนบนเตียงตลอดหรือเกือบตลอดเวลา พึ่งพาผู้ดูแลในทุกกิจวัตรประจำวัน',
    careGuidelines: 'แผนการดูแลเฉพาะบุคคล (Care Plan โดย Care Manager) ป้องกันแผลกดทับ ข้อติด ปอดอักเสบ ดูแลสายสวน/สายให้อาหาร เยี่ยมบ้านโดยทีมสหวิชาชีพอย่างน้อยสัปดาห์ละ 1-2 ครั้ง',
  },
};

export const LTC_GROUPS: Record<number, LTCGroupInfo> = {
  1: {
    group: 1,
    title: 'กลุ่มที่ 1 (LTC 1)',
    condition: 'เคลื่อนไหวได้ รับประทานอาหารได้ ไม่มีภาวะสมองเสื่อม',
    careFrequency: 'ติดตามเยี่ยมบ้าน 1 ครั้ง/เดือน',
    carePlanSummary: 'ส่งเสริมสุขภาพ กายภาพบำบัด ชะลอความเสื่อม สิทธิเงินอุดหนุนกองทุนตำบล',
  },
  2: {
    group: 2,
    title: 'กลุ่มที่ 2 (LTC 2)',
    condition: 'เคลื่อนไหวได้ รับประทานอาหารได้ แต่มีภาวะสมองเสื่อม หรือกลั้นการขับถ่ายไม่ได้',
    careFrequency: 'ติดตามเยี่ยมบ้าน 2 ครั้ง/เดือน',
    carePlanSummary: 'จัดหาผ้าอ้อมผู้ใหญ่/แผ่นรองซับ ดูแลความปลอดภัยป้องกันการพลัดหลงและล้ม',
  },
  3: {
    group: 3,
    title: 'กลุ่มที่ 3 (LTC 3)',
    condition: 'เคลื่อนไหวไม่ได้ หรือรับประทานอาหารเองไม่ได้ ไม่เจ็บป่วยรุนแรง',
    careFrequency: 'ติดตามเยี่ยมบ้าน 1-2 ครั้ง/สัปดาห์',
    carePlanSummary: 'จัดหาเตียงผู้ป่วย เบาะลม แผ่นรองซับ ป้องกันแผลกดทับ กายภาพบำบัดต่อเนื่อง',
  },
  4: {
    group: 4,
    title: 'กลุ่มที่ 4 (LTC 4)',
    condition: 'ติดเตียง มีภาวะเจ็บป่วยรุนแรง หรือต้องการการดูแลระยะประคับประคอง (Palliative)',
    careFrequency: 'ติดตามเยี่ยมบ้าน 2 ครั้ง/สัปดาห์ หรือตามแผนแพทย์',
    carePlanSummary: 'ทีมแพทย์/พยาบาลเยี่ยมบ้าน ดูแลอุปกรณ์ทางการแพทย์เฉพาะ (แผลกดทับ, สายสวน, ท่อช่วยหายใจ)',
  },
};

export const ADL_QUESTIONS: ADLItemDefinition[] = [
  {
    id: 'feeding',
    key: 'feeding',
    number: 1,
    title: 'การรับประทานอาหารเมื่อเตรียมสำรับไว้ให้เรียบร้อยต่อหน้า (Feeding)',
    subtitle: 'พิจารณาความสามารถในการตักอาหารเข้าปาก เคี้ยว และกลืนอาหาร',
    maxScore: 2,
    options: [
      { score: 0, label: '0 คะแนน', description: 'ไม่สามารถตักอาหารเข้าปากเองได้ ต้องมีคนป้อนให้ หรือต้องให้อาหารทางสายยาง' },
      { score: 1, label: '1 คะแนน', description: 'ตักอาหารเองได้ แต่ต้องมีคนช่วยเตรียมหรือหั่นให้เป็นชิ้นเล็กๆ หรือช่วยทาเนย' },
      { score: 2, label: '2 คะแนน', description: 'รับประทานได้เองตามลำพัง ตั้งแต่ตักอาหาร เคี้ยว และกลืนได้เรียบร้อย' },
    ],
  },
  {
    id: 'grooming',
    key: 'grooming',
    number: 2,
    title: 'การล้างหน้า แปรงฟัน หวีผม โกนหนวด (Grooming)',
    subtitle: 'พิจารณาการดูแลสุขอนามัยส่วนบุคคลในระยะ 24-48 ชั่วโมงที่ผ่านมา',
    maxScore: 1,
    options: [
      { score: 0, label: '0 คะแนน', description: 'ต้องการความช่วยเหลือจากผู้อื่น ไม่สามารถทำได้เอง' },
      { score: 1, label: '1 คะแนน', description: 'ทำได้เองทั้งหมด (รวมทั้งการโกนหนวด หวีผม แปรงฟัน และล้างหน้า)' },
    ],
  },
  {
    id: 'transfer',
    key: 'transfer',
    number: 3,
    title: 'การลุกนั่งจากที่นอน หรือจากเตียงไปยังเก้าอี้ (Transfer)',
    subtitle: 'พิจารณาความสามารถในการย้ายตัวจากเตียงไปนั่งเก้าอี้/รถเข็น',
    maxScore: 3,
    options: [
      { score: 0, label: '0 คะแนน', description: 'ไม่สามารถนั่งได้ นอนอยู่บนเตียงตลอดเวลา หรือต้องใช้ 2 คนยกตัว' },
      { score: 1, label: '1 คะแนน', description: 'ต้องการความช่วยเหลืออย่างมาก (ต้องมี 1-2 คนช่วยพยุงอย่างเต็มที่) สามารถนั่งทรงตัวได้' },
      { score: 2, label: '2 คะแนน', description: 'ต้องการความช่วยเหลือบ้าง (มีคนช่วยพยุง 1 คน หรือมีคนคอยดูแลเพื่อความปลอดภัย)' },
      { score: 3, label: '3 คะแนน', description: 'ทำได้เองทั้งหมด ลุกนั่งและย้ายตัวได้เองอย่างปลอดภัย' },
    ],
  },
  {
    id: 'toilet',
    key: 'toilet',
    number: 4,
    title: 'การใช้ห้องน้ำ (Toilet Use)',
    subtitle: 'พิจารณาการเข้าห้องน้ำ ถอด-ใส่เสื้อผ้า ทำความสะอาดหลังขับถ่าย และลุกขึ้น',
    maxScore: 2,
    options: [
      { score: 0, label: '0 คะแนน', description: 'ช่วยตัวเองไม่ได้เลย ต้องใช้กระโถนหรือผ้าอ้อม และผู้อื่นทำความสะอาดให้' },
      { score: 1, label: '1 คะแนน', description: 'ทำเองได้บ้าง ต้องการความช่วยเหลือในการทรงตัว ถอด/ใส่กางเกง หรือทำความสะอาด' },
      { score: 2, label: '2 คะแนน', description: 'ทำได้เองทั้งหมด เข้าห้องน้ำ ถอดใส่เสื้อผ้า ทำความสะอาดได้เองปลอดภัย' },
    ],
  },
  {
    id: 'mobility',
    key: 'mobility',
    number: 5,
    title: 'การเคลื่อนที่ภายในห้องหรือบ้าน (Mobility / Walking)',
    subtitle: 'พิจารณาการเดินบนพื้นราบระยะทางประมาณ 50 เมตร',
    maxScore: 3,
    options: [
      { score: 0, label: '0 คะแนน', description: 'เคลื่อนที่ไปไหนไม่ได้เลย หรือนั่งรถเข็นโดยไม่สามารถเข็นตัวเองได้' },
      { score: 1, label: '1 คะแนน', description: 'ใช้รถเข็นและสามารถเข็นตัวเองได้เลี้ยวได้ เป็นระยะทาง 50 เมตร' },
      { score: 2, label: '2 คะแนน', description: 'เดินได้โดยมีคนช่วยพยุง 1 คน หรือต้องใช้เครื่องช่วยเดิน (Walker/ไม้เท้า 4 ขา)' },
      { score: 3, label: '3 คะแนน', description: 'เดินได้เองตามลำพัง อาจใช้ไม้เท้าธรรมดาได้ เดินได้อย่างมั่นคง' },
    ],
  },
  {
    id: 'dressing',
    key: 'dressing',
    number: 6,
    title: 'การสวมใส่เสื้อผ้า (Dressing)',
    subtitle: 'พิจารณาการเลือกเสื้อผ้า สวมใส่ ติดกระดุม รูดซิป และสวมรองเท้า',
    maxScore: 2,
    options: [
      { score: 0, label: '0 คะแนน', description: 'ต้องมีคนช่วยใส่เสื้อผ้าให้ทั้งหมด ไม่สามารถช่วยตัวเองได้' },
      { score: 1, label: '1 คะแนน', description: 'ช่วยตัวเองได้บ้างอย่างน้อยครึ่งหนึ่ง แต่ต้องมีคนช่วยติดกระดุม หรือสวมกางเกง/ถุงเท้า' },
      { score: 2, label: '2 คะแนน', description: 'สวมใส่เสื้อผ้าได้เองทั้งหมด ติดกระดุม รูดซิป และผูกเชือกรองเท้าได้เอง' },
    ],
  },
  {
    id: 'stairs',
    key: 'stairs',
    number: 7,
    title: 'การขึ้นลงบันได 1 ชั้น (Stairs)',
    subtitle: 'พิจารณาการขึ้นลงบันไดประมาณ 8-10 ขั้น',
    maxScore: 2,
    options: [
      { score: 0, label: '0 คะแนน', description: 'ไม่สามารถขึ้นลงบันไดได้เลย' },
      { score: 1, label: '1 คะแนน', description: 'ขึ้นลงได้แต่ต้องมีคนช่วยพยุง หรือต้องคอยเฝ้าระวังอย่างใกล้ชิด' },
      { score: 2, label: '2 คะแนน', description: 'ขึ้นลงได้เองอย่างปลอดภัย (อาจจับราวบันไดหรือใช้ไม้เท้าได้)' },
    ],
  },
  {
    id: 'bathing',
    key: 'bathing',
    number: 8,
    title: 'การอาบน้ำ (Bathing)',
    subtitle: 'พิจารณาการอาบน้ำด้วยฝักบัว ตักอาบ หรือแช่ในอ่าง',
    maxScore: 1,
    options: [
      { score: 0, label: '0 คะแนน', description: 'ต้องมีคนช่วยอาบน้ำให้ หรือเช็ดตัวให้ทั้งหมด' },
      { score: 1, label: '1 คะแนน', description: 'อาบน้ำ ถูสบู่ ล้างตัว และเช็ดตัวได้เองทั้งหมด' },
    ],
  },
  {
    id: 'bowels',
    key: 'bowels',
    number: 9,
    title: 'การกลั้นการถ่ายอุจจาระ (Bowels / Continence)',
    subtitle: 'พิจารณาในระยะ 1 สัปดาห์ที่ผ่านมา',
    maxScore: 2,
    options: [
      { score: 0, label: '0 คะแนน', description: 'กลั้นไม่ได้เลย หรืออุจจาระราดเป็นประจำ หรือต้องสวนอุจจาระเสมอ' },
      { score: 1, label: '1 คะแนน', description: 'กลั้นไม่ได้เป็นบางครั้ง (เกิดขึ้นไม่เกิน 1 ครั้งในรอบสัปดาห์)' },
      { score: 2, label: '2 คะแนน', description: 'กลั้นได้เป็นปกติ ควบคุมการขับถ่ายอุจจาระได้ดี' },
    ],
  },
  {
    id: 'bladder',
    key: 'bladder',
    number: 10,
    title: 'การกลั้นการถ่ายปัสสาวะ (Bladder / Continence)',
    subtitle: 'พิจารณาในระยะ 1 สัปดาห์ที่ผ่านมา',
    maxScore: 2,
    options: [
      { score: 0, label: '0 คะแนน', description: 'กลั้นไม่ได้เลย ปัสสาวะราดเป็นประจำ หรือคาสายสวนปัสสาวะ (Foley\'s catheter)' },
      { score: 1, label: '1 คะแนน', description: 'กลั้นไม่ได้เป็นบางครั้ง (เกิดขึ้นไม่เกินวันละ 1 ครั้ง)' },
      { score: 2, label: '2 คะแนน', description: 'กลั้นได้เป็นปกติ ไม่มีการเล็ดราด' },
    ],
  },
];

// Helper to create Thai mock image SVG base64 for ID Cards and Patient photos
export function generateMockIdCardSvg(name: string, citizenId: string, address: string): string {
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 600 380" width="600" height="380">
    <defs>
      <linearGradient id="bg" x1="0%" y1="0%" x2="100%" y2="100%">
        <stop offset="0%" stop-color="#eff6ff" />
        <stop offset="50%" stop-color="#dbeafe" />
        <stop offset="100%" stop-color="#bfdbfe" />
      </linearGradient>
      <linearGradient id="flag" x1="0%" y1="0%" x2="100%" y2="0%">
        <stop offset="0%" stop-color="#ef4444" />
        <stop offset="16.6%" stop-color="#ef4444" />
        <stop offset="16.6%" stop-color="#ffffff" />
        <stop offset="33.3%" stop-color="#ffffff" />
        <stop offset="33.3%" stop-color="#1e3a8a" />
        <stop offset="66.6%" stop-color="#1e3a8a" />
        <stop offset="66.6%" stop-color="#ffffff" />
        <stop offset="83.3%" stop-color="#ffffff" />
        <stop offset="83.3%" stop-color="#ef4444" />
        <stop offset="100%" stop-color="#ef4444" />
      </linearGradient>
    </defs>
    <!-- Card Body -->
    <rect width="600" height="380" rx="20" fill="url(#bg)" stroke="#93c5fd" stroke-width="4"/>
    <!-- Flag stripe header -->
    <rect x="24" y="24" width="70" height="42" rx="4" fill="url(#flag)" stroke="#cbd5e1" stroke-width="1"/>
    <!-- Garuda silhouette placeholder -->
    <circle cx="300" cy="46" r="22" fill="#3b82f6" fill-opacity="0.15" />
    <path d="M 290 52 Q 300 35 310 52 Q 300 48 290 52 Z" fill="#1d4ed8" />
    
    <text x="110" y="42" font-family="Prompt, sans-serif" font-size="16" font-weight="bold" fill="#1e3a8a">บัตรประจำตัวประชาชน</text>
    <text x="110" y="60" font-family="sans-serif" font-size="12" fill="#475569">Thai National ID Card</text>
    
    <text x="110" y="96" font-family="monospace" font-size="20" font-weight="bold" fill="#0f172a" letter-spacing="3">${citizenId}</text>
    
    <!-- Chip -->
    <rect x="40" y="110" width="76" height="58" rx="6" fill="#f59e0b" stroke="#d97706" stroke-width="2"/>
    <line x1="40" y1="139" x2="116" y2="139" stroke="#b45309" stroke-width="2" />
    <line x1="78" y1="110" x2="78" y2="168" stroke="#b45309" stroke-width="2" />
    
    <!-- Photo Area -->
    <rect x="420" y="90" width="144" height="180" rx="10" fill="#ffffff" stroke="#94a3b8" stroke-width="2"/>
    <circle cx="492" cy="150" r="38" fill="#cbd5e1" />
    <path d="M 450 240 C 450 195 534 195 534 240 Z" fill="#94a3b8" />
    <text x="492" y="260" font-family="Prompt, sans-serif" font-size="11" fill="#64748b" text-anchor="middle">ภาพถ่ายจริง</text>
    
    <!-- Data lines -->
    <text x="40" y="200" font-family="Prompt, sans-serif" font-size="12" fill="#64748b">ชื่อตัวและชื่อสกุล:</text>
    <text x="150" y="200" font-family="Prompt, sans-serif" font-size="17" font-weight="bold" fill="#0f172a">${name}</text>
    
    <text x="40" y="235" font-family="Prompt, sans-serif" font-size="12" fill="#64748b">วันเกิด / Date of Birth:</text>
    <text x="170" y="235" font-family="Prompt, sans-serif" font-size="14" fill="#1e293b">15 ม.ค. 2492 / 15 Jan 1949</text>
    
    <text x="40" y="270" font-family="Prompt, sans-serif" font-size="12" fill="#64748b">ที่อยู่:</text>
    <text x="80" y="270" font-family="Prompt, sans-serif" font-size="13" fill="#1e293b">${address}</text>
    
    <!-- Footer line -->
    <rect x="24" y="320" width="552" height="34" rx="6" fill="#ffffff" fill-opacity="0.8"/>
    <text x="40" y="342" font-family="Prompt, sans-serif" font-size="12" fill="#475569">กรมการปกครอง กระทรวงมหาดไทย</text>
    <text x="550" y="342" font-family="monospace" font-size="12" fill="#64748b" text-anchor="end">BARTHEL-ADL-VERIFIED</text>
  </svg>`;
  return `data:image/svg+xml;utf8,${encodeURIComponent(svg)}`;
}

export function generateMockPatientPhotoSvg(name: string, gender: 'ชาย' | 'หญิง', age: number, category: string): string {
  const isFemale = gender === 'หญิง';
  const colorBg = category === 'bedridden' ? '#ffe4e6' : category === 'homebound' ? '#fef3c7' : '#d1fae5';
  const strokeColor = category === 'bedridden' ? '#f43f5e' : category === 'homebound' ? '#f59e0b' : '#10b981';
  
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 300 300" width="300" height="300">
    <rect width="300" height="300" fill="${colorBg}" rx="24"/>
    <!-- Head / Hair -->
    <circle cx="150" cy="115" r="55" fill="${isFemale ? '#e2e8f0' : '#cbd5e1'}" />
    <!-- Hair style -->
    ${isFemale 
      ? '<path d="M 95 120 C 95 60 205 60 205 120 C 200 95 180 85 150 85 C 120 85 100 95 95 120 Z" fill="#94a3b8" />' 
      : '<path d="M 100 100 C 100 70 200 70 200 100 C 185 85 165 80 150 80 C 135 80 115 85 100 100 Z" fill="#64748b" />'}
    <!-- Face -->
    <circle cx="150" cy="125" r="44" fill="#fde68a" />
    <!-- Glasses -->
    <rect x="122" y="115" width="22" height="16" rx="4" fill="none" stroke="#475569" stroke-width="2"/>
    <rect x="156" y="115" width="22" height="16" rx="4" fill="none" stroke="#475569" stroke-width="2"/>
    <line x1="144" y1="123" x2="156" y2="123" stroke="#475569" stroke-width="2"/>
    <!-- Smile -->
    <path d="M 138 145 Q 150 155 162 145" fill="none" stroke="#b45309" stroke-width="2" stroke-linecap="round"/>
    <!-- Shoulders -->
    <path d="M 60 270 C 60 190 240 190 240 270 Z" fill="${isFemale ? '#38bdf8' : '#64748b'}" />
    <!-- Badge -->
    <circle cx="150" cy="275" r="16" fill="${strokeColor}" />
    <text x="150" y="280" font-family="Prompt, sans-serif" font-size="10" font-weight="bold" fill="#ffffff" text-anchor="middle">${age}ปี</text>
  </svg>`;
  return `data:image/svg+xml;utf8,${encodeURIComponent(svg)}`;
}

// Initial 8 patient records across the 8 requested villages
export const INITIAL_PATIENTS: Patient[] = [
  {
    id: 'pt-001',
    prefix: 'นาย',
    firstName: 'สมหมาย',
    lastName: 'บุญมี',
    citizenId: '3-4101-00234-51-1',
    birthDate: '1947-04-12',
    age: 79,
    gender: 'ชาย',
    phone: '081-234-5678',
    houseNumber: '45/1',
    street: 'ถ.มิตรภาพชุมชน',
    villageId: 1,
    villageName: 'หมู่ 1 บ้านธาตุ',
    subdistrict: 'ตำบลบ้านธาตุ',
    district: 'อำเภอเมือง',
    province: 'จังหวัดอุดรธานี',
    postalCode: '41000',
    landmarks: 'ตรงข้ามศาลากลางหมู่ 1 หลังวัดบ้านธาตุ',
    caregiver: {
      name: 'นางมาลี บุญมี',
      relationship: 'ภรรยา',
      phone: '089-876-5432',
      isMainCaregiver: true,
    },
    healthRights: 'บัตรทอง (UC)',
    chronicDiseases: ['โรคหลอดเลือดสมอง (Stroke)', 'ความดันโลหิตสูง', 'โรคเบาหวาน'],
    specialConditions: {
      hasBedsores: true,
      bedsoresStage: 'ระดับ 2 (แผลบริเวณก้นกบ)',
      hasFoleyCatheter: true,
      hasNGTube: false,
      hasTracheostomy: false,
      cognitiveImpairment: 'mild',
      visualImpairment: false,
      hearingImpairment: true,
      paralysisType: 'hemiplegia',
    },
    idCardPhoto: generateMockIdCardSvg('นายสมหมาย บุญมี', '3-4101-00234-51-1', '45/1 หมู่ 1 บ้านธาตุ ต.บ้านธาตุ อ.เมือง จ.อุดรธานี'),
    patientPhoto: generateMockPatientPhotoSvg('นายสมหมาย บุญมี', 'ชาย', 79, 'bedridden'),
    currentADL: {
      id: 'adl-001',
      assessmentDate: '2026-09-15',
      assessmentRound: 1,
      evaluatorName: 'นางสาวพัชราภรณ์ สุขใจ',
      evaluatorRole: 'พยาบาลวิชาชีพ / Care Manager',
      evaluatorAgency: 'รพ.สต.บ้านธาตุ',
      answers: {
        feeding: 1,
        grooming: 0,
        transfer: 0,
        toilet: 0,
        mobility: 0,
        dressing: 0,
        stairs: 0,
        bathing: 0,
        bowels: 1,
        bladder: 0,
      },
      totalScore: 2,
      category: 'bedridden',
      ltcGroup: 4,
      clinicalNotes: 'ผู้ป่วยมีอัมพาตซีกซ้ายจากโรคหลอดเลือดสมอง คาสายสวนปัสสาวะ มีแผลกดทับระดับ 2 บริเวณก้นกบ ต้องพลิกตัวทุก 2 ชั่วโมง แนะนำที่นอนลมและกายภาพบำบัด',
      suggestedEquipments: ['ที่นอนลมป้องกันแผลกดทับ', 'เตียงปรับระดับ 2 ไก', 'ผ้าอ้อมผู้ใหญ่', 'แผ่นรองซับ'],
    },
    assessmentHistory: [],
    createdAt: '2026-09-15T09:00:00Z',
    updatedAt: '2026-09-15T09:00:00Z',
  },
  {
    id: 'pt-002',
    prefix: 'นาง',
    firstName: 'บัวลอย',
    lastName: 'คำภา',
    citizenId: '3-4101-00567-89-2',
    birthDate: '1951-08-20',
    age: 75,
    gender: 'หญิง',
    phone: '086-555-1234',
    houseNumber: '12',
    street: 'ซอยร่วมใจ',
    villageId: 2,
    villageName: 'หมู่ 2 บ้านงินโงม',
    subdistrict: 'ตำบลบ้านธาตุ',
    district: 'อำเภอเมือง',
    province: 'จังหวัดอุดรธานี',
    postalCode: '41000',
    landmarks: 'ใกล้ร้านค้าป้าแต๋ว ต้นไทรใหญ่',
    caregiver: {
      name: 'นายประสิทธิ์ คำภา',
      relationship: 'บุตรชาย',
      phone: '081-999-8877',
      isMainCaregiver: true,
    },
    healthRights: 'บัตรทอง (UC)',
    chronicDiseases: ['ข้อเข่าเสื่อม 2 ข้าง', 'ความดันโลหิตสูง', 'กระดูกพรุน'],
    specialConditions: {
      hasBedsores: false,
      hasFoleyCatheter: false,
      hasNGTube: false,
      hasTracheostomy: false,
      cognitiveImpairment: 'none',
      visualImpairment: false,
      hearingImpairment: false,
      paralysisType: 'none',
    },
    idCardPhoto: generateMockIdCardSvg('นางบัวลอย คำภา', '3-4101-00567-89-2', '12 หมู่ 2 บ้านงินโงม ต.บ้านธาตุ อ.เมือง จ.อุดรธานี'),
    patientPhoto: generateMockPatientPhotoSvg('นางบัวลอย คำภา', 'หญิง', 75, 'homebound'),
    currentADL: {
      id: 'adl-002',
      assessmentDate: '2026-09-18',
      assessmentRound: 1,
      evaluatorName: 'นายบุญเลิศ มั่นคง',
      evaluatorRole: 'อสม.',
      evaluatorAgency: 'รพ.สต.บ้านธาตุ',
      answers: {
        feeding: 2,
        grooming: 1,
        transfer: 2,
        toilet: 1,
        mobility: 2,
        dressing: 1,
        stairs: 0,
        bathing: 0,
        bowels: 2,
        bladder: 2,
      },
      totalScore: 11,
      category: 'homebound',
      ltcGroup: 2,
      clinicalNotes: 'เดินช้า ใช้ไม้เท้าพยุง ปวดข้อเข่ารุนแรง ขึ้นลงบันไดไม่ได้ อาบน้ำต้องมีคนช่วยพยุงเพื่อป้องกันการล้ม',
      suggestedEquipments: ['เก้าอี้นั่งถ่ายในห้องน้ำ', 'ไม้เท้า 4 ขา (Quad cane)', 'ราวจับในห้องน้ำ'],
    },
    assessmentHistory: [],
    createdAt: '2026-09-18T10:30:00Z',
    updatedAt: '2026-09-18T10:30:00Z',
  },
  {
    id: 'pt-003',
    prefix: 'นาย',
    firstName: 'ทองสา',
    lastName: 'วิเศษศรี',
    citizenId: '3-4101-00890-12-3',
    birthDate: '1944-11-03',
    age: 81,
    gender: 'ชาย',
    phone: '084-321-9876',
    houseNumber: '88/2',
    street: 'ถนนประชาพัฒนา',
    villageId: 3,
    villageName: 'หมู่ 3 บ้านโนนสร้างไพ',
    subdistrict: 'ตำบลบ้านธาตุ',
    district: 'อำเภอเมือง',
    province: 'จังหวัดอุดรธานี',
    postalCode: '41000',
    landmarks: 'ติดโรงเรียนบ้านโนนสร้างไพ รั้วสีเขียว',
    caregiver: {
      name: 'นางวิไลพร วิเศษศรี',
      relationship: 'บุตรสาว',
      phone: '082-111-2233',
      isMainCaregiver: true,
    },
    healthRights: 'ข้าราชการบำนาญ',
    chronicDiseases: ['โรคพาร์กินสัน (Parkinson)', 'เบาหวาน'],
    specialConditions: {
      hasBedsores: false,
      hasFoleyCatheter: false,
      hasNGTube: false,
      hasTracheostomy: false,
      cognitiveImpairment: 'moderate',
      visualImpairment: false,
      hearingImpairment: true,
      paralysisType: 'none',
    },
    idCardPhoto: generateMockIdCardSvg('นายทองสา วิเศษศรี', '3-4101-00890-12-3', '88/2 หมู่ 3 บ้านโนนสร้างไพ ต.บ้านธาตุ อ.เมือง จ.อุดรธานี'),
    patientPhoto: generateMockPatientPhotoSvg('นายทองสา วิเศษศรี', 'ชาย', 81, 'homebound'),
    currentADL: {
      id: 'adl-003',
      assessmentDate: '2026-09-20',
      assessmentRound: 1,
      evaluatorName: 'นางประภาศรี วงศ์ษา',
      evaluatorRole: 'อสม.',
      evaluatorAgency: 'รพ.สต.บ้านธาตุ',
      answers: {
        feeding: 1,
        grooming: 1,
        transfer: 1,
        toilet: 1,
        mobility: 1,
        dressing: 1,
        stairs: 0,
        bathing: 0,
        bowels: 1,
        bladder: 1,
      },
      totalScore: 7,
      category: 'homebound',
      ltcGroup: 2,
      clinicalNotes: 'มือสั่น ตัวเกร็ง เคลื่อนไหวช้า ทรงตัวไม่มั่นคง ต้องมีผู้ดูแลช่วยเหลืออย่างใกล้ชิดเรื่องการเดินและกลั้นปัสสาวะ',
      suggestedEquipments: ['วอล์กเกอร์แบบมีล้อ (Rollator)', 'ผ้าอ้อมผู้ใหญ่สำเร็จรูป'],
    },
    assessmentHistory: [],
    createdAt: '2026-09-20T11:15:00Z',
    updatedAt: '2026-09-20T11:15:00Z',
  },
  {
    id: 'pt-004',
    prefix: 'นาง',
    firstName: 'คำมูล',
    lastName: 'จันทร์แดง',
    citizenId: '3-4101-00345-67-4',
    birthDate: '1954-02-14',
    age: 72,
    gender: 'หญิง',
    phone: '087-654-3210',
    houseNumber: '5',
    street: 'ริมหนองหอย',
    villageId: 4,
    villageName: 'หมู่ 4 บ้านหนองหอย',
    subdistrict: 'ตำบลบ้านธาตุ',
    district: 'อำเภอเมือง',
    province: 'จังหวัดอุดรธานี',
    postalCode: '41000',
    landmarks: 'ติดศาลาริมน้ำหนองหอย',
    caregiver: {
      name: 'นายมนัส จันทร์แดง',
      relationship: 'สามี',
      phone: '087-654-3211',
      isMainCaregiver: true,
    },
    healthRights: 'บัตรทอง (UC)',
    chronicDiseases: ['ไขมันในเลือดสูง', 'โรคข้อเข่าเสื่อม'],
    specialConditions: {
      hasBedsores: false,
      hasFoleyCatheter: false,
      hasNGTube: false,
      hasTracheostomy: false,
      cognitiveImpairment: 'none',
      visualImpairment: false,
      hearingImpairment: false,
      paralysisType: 'none',
    },
    idCardPhoto: generateMockIdCardSvg('นางคำมูล จันทร์แดง', '3-4101-00345-67-4', '5 หมู่ 4 บ้านหนองหอย ต.บ้านธาตุ อ.เมือง จ.อุดรธานี'),
    patientPhoto: generateMockPatientPhotoSvg('นางคำมูล จันทร์แดง', 'หญิง', 72, 'social'),
    currentADL: {
      id: 'adl-004',
      assessmentDate: '2026-09-22',
      assessmentRound: 1,
      evaluatorName: 'นายสมชาย คำมี',
      evaluatorRole: 'อสม.',
      evaluatorAgency: 'รพ.สต.บ้านธาตุ',
      answers: {
        feeding: 2,
        grooming: 1,
        transfer: 3,
        toilet: 2,
        mobility: 3,
        dressing: 2,
        stairs: 1,
        bathing: 1,
        bowels: 2,
        bladder: 2,
      },
      totalScore: 19,
      category: 'social',
      ltcGroup: 1,
      clinicalNotes: 'ช่วยเหลือตัวเองได้ดีเยี่ยม ร่วมกิจกรรมชมรมผู้สูงอายุสม่ำเสมอ มีเพียงอาการเมื่อยเข่าเวลาขึ้นบันไดสูง',
      suggestedEquipments: ['แผ่นยางกันลื่นห้องน้ำ'],
    },
    assessmentHistory: [],
    createdAt: '2026-09-22T08:45:00Z',
    updatedAt: '2026-09-22T08:45:00Z',
  },
  {
    id: 'pt-005',
    prefix: 'นาย',
    firstName: 'บุญมี',
    lastName: 'ศรีกระจ่าง',
    citizenId: '3-4101-00123-99-5',
    birthDate: '1940-07-09',
    age: 86,
    gender: 'ชาย',
    phone: '085-444-3322',
    houseNumber: '109',
    street: 'ซอยวัดคันชา',
    villageId: 5,
    villageName: 'หมู่ 5 บ้านคันชา',
    subdistrict: 'ตำบลบ้านธาตุ',
    district: 'อำเภอเมือง',
    province: 'จังหวัดอุดรธานี',
    postalCode: '41000',
    landmarks: 'ซอยตรงข้ามทางเข้าวัดคันชา บ้านไม้สองชั้น',
    caregiver: {
      name: 'นางสมพร ศรีกระจ่าง',
      relationship: 'ลูกสะใภ้',
      phone: '085-444-3323',
      isMainCaregiver: true,
    },
    healthRights: 'บัตรทอง (UC)',
    chronicDiseases: ['สมองเสื่อมขั้นรุนแรง (Alzheimer\'s)', 'โรคไตวายเรื้อรัง'],
    specialConditions: {
      hasBedsores: true,
      bedsoresStage: 'ระดับ 1 (ผิวหนังแดงไม่จางหาย)',
      hasFoleyCatheter: false,
      hasNGTube: true,
      hasTracheostomy: false,
      cognitiveImpairment: 'severe',
      visualImpairment: false,
      hearingImpairment: true,
      paralysisType: 'paraplegia',
    },
    idCardPhoto: generateMockIdCardSvg('นายบุญมี ศรีกระจ่าง', '3-4101-00123-99-5', '109 หมู่ 5 บ้านคันชา ต.บ้านธาตุ อ.เมือง จ.อุดรธานี'),
    patientPhoto: generateMockPatientPhotoSvg('นายบุญมี ศรีกระจ่าง', 'ชาย', 86, 'bedridden'),
    currentADL: {
      id: 'adl-005',
      assessmentDate: '2026-09-25',
      assessmentRound: 1,
      evaluatorName: 'นางทองม้วน ศรีสุข',
      evaluatorRole: 'อสม. / CG',
      evaluatorAgency: 'รพ.สต.บ้านธาตุ',
      answers: {
        feeding: 0,
        grooming: 0,
        transfer: 0,
        toilet: 0,
        mobility: 0,
        dressing: 0,
        stairs: 0,
        bathing: 0,
        bowels: 0,
        bladder: 0,
      },
      totalScore: 0,
      category: 'bedridden',
      ltcGroup: 4,
      clinicalNotes: 'ผู้ป่วยติดเตียงโดยสิ้นเชิง ให้อาหารทางสายยาง NG Tube ควบคุมการขับถ่ายไม่ได้ จำญาติไม่ได้ ต้องการการดูแลพิเศษเพื่อป้องกันแผลกดทับและปอดอักเสบสำลัก',
      suggestedEquipments: ['เตียงผู้ป่วย 3 ไก', 'ที่นอนลม', 'เครื่องดูดเสมหะ', 'อาหารทางการแพทย์'],
    },
    assessmentHistory: [],
    createdAt: '2026-09-25T14:20:00Z',
    updatedAt: '2026-09-25T14:20:00Z',
  },
  {
    id: 'pt-006',
    prefix: 'นางสาว',
    firstName: 'บัวผัน',
    lastName: 'จันทรโคตร์',
    citizenId: '3-4101-00789-45-6',
    birthDate: '1949-12-05',
    age: 76,
    gender: 'หญิง',
    phone: '083-777-6655',
    houseNumber: '24',
    street: 'ถนนกลางหมู่บ้าน',
    villageId: 6,
    villageName: 'หมู่ 6 บ้านโคกหลวง',
    subdistrict: 'ตำบลบ้านธาตุ',
    district: 'อำเภอเมือง',
    province: 'จังหวัดอุดรธานี',
    postalCode: '41000',
    landmarks: 'หน้าลานกีฬาชุมชนโคกหลวง',
    caregiver: {
      name: 'นายสุริยา จันทรโคตร์',
      relationship: 'หลานชาย',
      phone: '083-777-6656',
      isMainCaregiver: true,
    },
    healthRights: 'บัตรทอง (UC)',
    chronicDiseases: ['เบาหวาน', 'ความดันโลหิตสูง', 'ตามัวจากต้อกระจก'],
    specialConditions: {
      hasBedsores: false,
      hasFoleyCatheter: false,
      hasNGTube: false,
      hasTracheostomy: false,
      cognitiveImpairment: 'mild',
      visualImpairment: true,
      hearingImpairment: false,
      paralysisType: 'hemiparesis',
    },
    idCardPhoto: generateMockIdCardSvg('นางสาวบัวผัน จันทรโคตร์', '3-4101-00789-45-6', '24 หมู่ 6 บ้านโคกหลวง ต.บ้านธาตุ อ.เมือง จ.อุดรธานี'),
    patientPhoto: generateMockPatientPhotoSvg('นางสาวบัวผัน จันทรโคตร์', 'หญิง', 76, 'homebound'),
    currentADL: {
      id: 'adl-006',
      assessmentDate: '2026-09-28',
      assessmentRound: 1,
      evaluatorName: 'นายสุวิทย์ ศรีวิลัย',
      evaluatorRole: 'อสม.',
      evaluatorAgency: 'รพ.สต.บ้านธาตุ',
      answers: {
        feeding: 2,
        grooming: 1,
        transfer: 2,
        toilet: 1,
        mobility: 1,
        dressing: 1,
        stairs: 0,
        bathing: 0,
        bowels: 1,
        bladder: 1,
      },
      totalScore: 9,
      category: 'homebound',
      ltcGroup: 2,
      clinicalNotes: 'สายตามัว แขนขาข้างขวาอ่อนแรงเล็กน้อย เดินในบ้านได้ช้า ต้องระวังสะดุดล้ม ต้องการราวจับตามผนังบ้านและห้องน้ำ',
      suggestedEquipments: ['ราวจับติดผนัง', 'เก้าอี้อาบน้ำ', 'แว่นขยายช่วยอ่าน'],
    },
    assessmentHistory: [],
    createdAt: '2026-09-28T09:10:00Z',
    updatedAt: '2026-09-28T09:10:00Z',
  },
  {
    id: 'pt-007',
    prefix: 'นาย',
    firstName: 'สนิท',
    lastName: 'แสงสุวรรณ',
    citizenId: '3-4101-00432-11-7',
    birthDate: '1953-06-18',
    age: 73,
    gender: 'ชาย',
    phone: '088-222-1144',
    houseNumber: '67',
    street: 'ซอยเจริญสุข',
    villageId: 7,
    villageName: 'หมู่ 7 บ้านเดิด',
    subdistrict: 'ตำบลบ้านธาตุ',
    district: 'อำเภอเมือง',
    province: 'จังหวัดอุดรธานี',
    postalCode: '41000',
    landmarks: 'ข้างหนองน้ำบ้านเดิด บ้านปูนชั้นเดียวสีฟ้า',
    caregiver: {
      name: 'นางกัลยา แสงสุวรรณ',
      relationship: 'ภรรยา',
      phone: '088-222-1145',
      isMainCaregiver: true,
    },
    healthRights: 'บัตรทอง (UC)',
    chronicDiseases: ['ความดันโลหิตสูง', 'ไขมัน'],
    specialConditions: {
      hasBedsores: false,
      hasFoleyCatheter: false,
      hasNGTube: false,
      hasTracheostomy: false,
      cognitiveImpairment: 'none',
      visualImpairment: false,
      hearingImpairment: false,
      paralysisType: 'none',
    },
    idCardPhoto: generateMockIdCardSvg('นายสนิท แสงสุวรรณ', '3-4101-00432-11-7', '67 หมู่ 7 บ้านเดิด ต.บ้านธาตุ อ.เมือง จ.อุดรธานี'),
    patientPhoto: generateMockPatientPhotoSvg('นายสนิท แสงสุวรรณ', 'ชาย', 73, 'social'),
    currentADL: {
      id: 'adl-007',
      assessmentDate: '2026-10-01',
      assessmentRound: 1,
      evaluatorName: 'นางรำไพ พลเยี่ยม',
      evaluatorRole: 'อสม.',
      evaluatorAgency: 'รพ.สต.บ้านธาตุ',
      answers: {
        feeding: 2,
        grooming: 1,
        transfer: 3,
        toilet: 2,
        mobility: 3,
        dressing: 2,
        stairs: 2,
        bathing: 1,
        bowels: 2,
        bladder: 2,
      },
      totalScore: 20,
      category: 'social',
      ltcGroup: 1,
      clinicalNotes: 'สุขภาพแข็งแรง ช่วยเหลือตัวเองได้ครบถ้วน เดินไปสวนไปวัดได้ แนะนำตรวจสุขภาพประจำปีสม่ำเสมอ',
      suggestedEquipments: [],
    },
    assessmentHistory: [],
    createdAt: '2026-10-01T15:00:00Z',
    updatedAt: '2026-10-01T15:00:00Z',
  },
  {
    id: 'pt-008',
    prefix: 'นาง',
    firstName: 'คำตา',
    lastName: 'บุญมีศรี',
    citizenId: '3-4101-00998-77-8',
    birthDate: '1946-03-30',
    age: 80,
    gender: 'หญิง',
    phone: '082-998-7766',
    houseNumber: '19/3',
    street: 'ซอยต้นเดื่อ',
    villageId: 8,
    villageName: 'หมู่ 8 บ้านเดื่อ',
    subdistrict: 'ตำบลบ้านธาตุ',
    district: 'อำเภอเมือง',
    province: 'จังหวัดอุดรธานี',
    postalCode: '41000',
    landmarks: 'ซอยข้าง อบต. ตรงข้ามต้นมะเดื่อใหญ่',
    caregiver: {
      name: 'นายประสิทธิ์ บุญมีศรี',
      relationship: 'บุตรชาย',
      phone: '082-998-7767',
      isMainCaregiver: true,
    },
    healthRights: 'บัตรทอง (UC)',
    chronicDiseases: ['โรคหลอดเลือดสมอง', 'ความดันโลหิตสูง'],
    specialConditions: {
      hasBedsores: false,
      hasFoleyCatheter: true,
      hasNGTube: false,
      hasTracheostomy: false,
      cognitiveImpairment: 'mild',
      visualImpairment: false,
      hearingImpairment: false,
      paralysisType: 'hemiplegia',
    },
    idCardPhoto: generateMockIdCardSvg('นางคำตา บุญมีศรี', '3-4101-00998-77-8', '19/3 หมู่ 8 บ้านเดื่อ ต.บ้านธาตุ อ.เมือง จ.อุดรธานี'),
    patientPhoto: generateMockPatientPhotoSvg('นางคำตา บุญมีศรี', 'หญิง', 80, 'bedridden'),
    currentADL: {
      id: 'adl-008',
      assessmentDate: '2026-10-03',
      assessmentRound: 1,
      evaluatorName: 'นายอำนวย บุญมี',
      evaluatorRole: 'ผู้ดูแล (CG) / อสม.',
      evaluatorAgency: 'รพ.สต.บ้านธาตุ',
      answers: {
        feeding: 1,
        grooming: 0,
        transfer: 1,
        toilet: 0,
        mobility: 0,
        dressing: 0,
        stairs: 0,
        bathing: 0,
        bowels: 1,
        bladder: 0,
      },
      totalScore: 3,
      category: 'bedridden',
      ltcGroup: 4,
      clinicalNotes: 'ผู้ป่วยอัมพาตครึ่งซีก คาสายสวนปัสสาวะ นั่งได้เมื่อมีคนช่วยพยุง กินอาหารเองได้บ้างแต่ต้องมีคนป้อนช่วย ต้องการการดูแลใกล้ชิด',
      suggestedEquipments: ['รถเข็นวีลแชร์แบบปรับเอนได้', 'ที่นอนลม', 'สายสวนปัสสาวะและถุงปัสสาวะ'],
    },
    assessmentHistory: [],
    createdAt: '2026-10-03T10:00:00Z',
    updatedAt: '2026-10-03T10:00:00Z',
  },
];
